export const ADD_MESSAGE = "ADD_MESSAGE";
export const LOADED_CHATS = "LOADED_CHATS";
export const ADD_MESSAGE_BULK = "ADD_MESSAGE_BULK";

export const ADD_CURRENT_CHAT = "ADD_CURRENT_CHAT";
export const RESET_CURRENT_CHAT = "RESET_CURRENT_CHAT";

export const DISPATCH_NOTIFICATION = "DISPATCH_NOTIFICATION";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const AUTHENTICATE_USER_REQUEST = "AUTHENTICATE_USER_REQUEST";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_FAILURE = "AUTHENTICATE_USER_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const GET_USER_CONTACTS_REQUEST = "GET_USER_CONTACTS_REQUEST";
export const GET_USER_CONTACTS_SUCCESS = "GET_USER_CONTACTS_SUCCESS";
export const GET_USER_CONTACTS_FAILURE = "GET_USER_CONTACTS_FAILURE";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_ARCHIVED_CHATS_REQUEST = "GET_ARCHIVED_CHATS_REQUEST";
export const GET_ARCHIVED_CHATS_SUCCESS = "GET_ARCHIVED_CHATS_SUCCESS";
export const GET_ARCHIVED_CHATS_FAILURE = "GET_ARCHIVED_CHATS_FAILURE";

export const ADD_CHAT_REQUEST = "ADD_CHAT_REQUEST";
export const ADD_CHAT_SUCCESS = "ADD_CHAT_SUCCESS";
export const ADD_CHAT_FAILURE = "ADD_CHAT_FAILURE";
export const ADD_CHAT_RESET = "ADD_CHAT_RESET";

export const DELETE_CHAT_REQUEST = "DELETE_CHAT_REQUEST";
export const DELETE_CHAT_SUCCESS = "DELETE_CHAT_SUCCESS";
export const DELETE_CHAT_FAILURE = "DELETE_CHAT_FAILURE";
export const DELETE_CHAT_RESET = "DELETE_CHAT_RESET";

export const ARCHIVE_CHAT_REQUEST = "ARCHIVE_CHAT_REQUEST";
export const ARCHIVE_CHAT_SUCCESS = "ARCHIVE_CHAT_SUCCESS";
export const ARCHIVE_CHAT_FAILURE = "ARCHIVE_CHAT_FAILURE";
export const ARCHIVE_CHAT_RESET = "ARCHIVE_CHAT_RESET";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const SAVE_MESSAGE_REQUEST = "SAVE_MESSAGE_REQUEST";
export const SAVE_MESSAGE_SUCCESS = "SAVE_MESSAGE_SUCCESS";
export const SAVE_MESSAGE_FAILURE = "SAVE_MESSAGE_FAILURE";
export const SAVE_MESSAGE_RESET = "SAVE_MESSAGE_RESET";

export const LOAD_MESSAGES_REQUEST = "LOAD_MESSAGES_REQUEST";
export const LOAD_MESSAGES_SUCCESS = "LOAD_MESSAGES_SUCCESS";
export const LOAD_MESSAGES_FAILURE = "LOAD_MESSAGES_FAILURE";
export const LOAD_MESSAGES_RESET = "LOAD_MESSAGES_RESET";
